Database:
  host: ~
  port: 3306
  user: root
  password: root
  database: test
  table: zaphkiel_database

Durability:
  display: '&8[ &f%symbol% &8]'
  display-symbol:
    0: ◆
    1: ◇

InternetItem:
  item:
  # - https://.../item-internet.yml
  display:
  # - https://.../display-internet.yml